- name: Get distribution
  command: lsb_release -sc
  register: distribution

- name: Get architecture
  command: dpkg --print-architecture
  register: architecture

- name: Install dependencies
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Download gpg key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker.gpg_armored
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

- name: De-Armor gpg key
  shell: gpg --dearmor < /usr/share/keyrings/docker.gpg_armored > /usr/share/keyrings/docker.gpg
  args:
    creates: /usr/share/keyrings/docker.gpg

- name: Add repository
  apt_repository:
    repo: deb [arch={{architecture.stdout}} signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian {{distribution.stdout}} stable
    state: present

- name: Install docker
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Start service
  service:
    name: docker
    state: started
    enabled: yes
